package com.model.po;
// Generated 2018-7-6 14:29:52 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CurrentUserInfo generated by hbm2java
 */
@Entity
@Table(name = "CurrentUserInfo", catalog = "SimulatorManagement")
public class CurrentUserInfo implements java.io.Serializable {

	private String simulatorId;
	private SimulatorInfo simulatorInfo;
	private String trainUnitCode;
	private String pupilNo;
	private String pupilName;
	private String cardNo;
	private String equipmentType;
	private byte stat;
	private int time;

	public CurrentUserInfo() {
	}

	public CurrentUserInfo(String simulatorId, SimulatorInfo simulatorInfo, String trainUnitCode, String pupilNo,
			String pupilName, String cardNo, String equipmentType, byte stat, int time) {
		this.simulatorId = simulatorId;
		this.simulatorInfo = simulatorInfo;
		this.trainUnitCode = trainUnitCode;
		this.pupilNo = pupilNo;
		this.pupilName = pupilName;
		this.cardNo = cardNo;
		this.equipmentType = equipmentType;
		this.stat = stat;
		this.time = time;
	}

	@Id

	@Column(name = "simulatorId", unique = true, nullable = false, length = 64)
	public String getSimulatorId() {
		return this.simulatorId;
	}

	public void setSimulatorId(String simulatorId) {
		this.simulatorId = simulatorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EQUIPMENT_ID", nullable = false)
	public SimulatorInfo getSimulatorInfo() {
		return this.simulatorInfo;
	}

	public void setSimulatorInfo(SimulatorInfo simulatorInfo) {
		this.simulatorInfo = simulatorInfo;
	}

	@Column(name = "TRAIN_UNIT_CODE", nullable = false, length = 64)
	public String getTrainUnitCode() {
		return this.trainUnitCode;
	}

	public void setTrainUnitCode(String trainUnitCode) {
		this.trainUnitCode = trainUnitCode;
	}

	@Column(name = "pupilNo", nullable = false, length = 64)
	public String getPupilNo() {
		return this.pupilNo;
	}

	public void setPupilNo(String pupilNo) {
		this.pupilNo = pupilNo;
	}

	@Column(name = "pupilName", nullable = false, length = 64)
	public String getPupilName() {
		return this.pupilName;
	}

	public void setPupilName(String pupilName) {
		this.pupilName = pupilName;
	}

	@Column(name = "cardNo", nullable = false, length = 18)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "EQUIPMENT_TYPE", nullable = false, length = 16)
	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	@Column(name = "STAT", nullable = false)
	public byte getStat() {
		return this.stat;
	}

	public void setStat(byte stat) {
		this.stat = stat;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

}
