package com.model.po;
// Generated 2018-7-6 14:29:52 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DriveTrainCompanyInfoAll generated by hbm2java
 */
@Entity
@Table(name = "DriveTrainCompanyInfo_all", catalog = "SimulatorManagement", uniqueConstraints = @UniqueConstraint(columnNames = "numId"))
public class DriveTrainCompanyInfoAll implements java.io.Serializable {

	private String trainUnitCode;
	private String numId;
	private String name;

	public DriveTrainCompanyInfoAll() {
	}

	public DriveTrainCompanyInfoAll(String trainUnitCode, String numId) {
		this.trainUnitCode = trainUnitCode;
		this.numId = numId;
	}

	public DriveTrainCompanyInfoAll(String trainUnitCode, String numId, String name) {
		this.trainUnitCode = trainUnitCode;
		this.numId = numId;
		this.name = name;
	}

	@Id

	@Column(name = "trainUnitCode", unique = true, nullable = false)
	public String getTrainUnitCode() {
		return this.trainUnitCode;
	}

	public void setTrainUnitCode(String trainUnitCode) {
		this.trainUnitCode = trainUnitCode;
	}

	@Column(name = "numId", unique = true, nullable = false, length = 20)
	public String getNumId() {
		return this.numId;
	}

	public void setNumId(String numId) {
		this.numId = numId;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
