package com.model.po;
// Generated 2018-7-6 14:29:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QueryRecord generated by hbm2java
 */
@Entity
@Table(name = "QueryRecord", catalog = "SimulatorManagement")
public class QueryRecord implements java.io.Serializable {

	private Integer id;
	private SimulatorInfo simulatorInfo;
	private Date time;

	public QueryRecord() {
	}

	public QueryRecord(SimulatorInfo simulatorInfo, Date time) {
		this.simulatorInfo = simulatorInfo;
		this.time = time;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipmentId", nullable = false)
	public SimulatorInfo getSimulatorInfo() {
		return this.simulatorInfo;
	}

	public void setSimulatorInfo(SimulatorInfo simulatorInfo) {
		this.simulatorInfo = simulatorInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
