package com.model.po;
// Generated 2018-7-6 14:29:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SimulatorInfo generated by hbm2java
 */
@Entity
@Table(name = "SimulatorInfo", catalog = "SimulatorManagement")
public class SimulatorInfo implements java.io.Serializable {

	private String equipmentId;
	private DriveTrainCompanyInfo driveTrainCompanyInfo;
	private String equipmentCode;
	private short stat;
	private String lastUser;
	private String equipmentType;
	private Set<CurrentUserInfo> currentUserInfos = new HashSet<CurrentUserInfo>(0);
	private Set<QueryRecord> queryRecords = new HashSet<QueryRecord>(0);

	public SimulatorInfo() {
	}

	public SimulatorInfo(String equipmentId, DriveTrainCompanyInfo driveTrainCompanyInfo, String equipmentCode,
			short stat, String equipmentType) {
		this.equipmentId = equipmentId;
		this.driveTrainCompanyInfo = driveTrainCompanyInfo;
		this.equipmentCode = equipmentCode;
		this.stat = stat;
		this.equipmentType = equipmentType;
	}

	public SimulatorInfo(String equipmentId, DriveTrainCompanyInfo driveTrainCompanyInfo, String equipmentCode,
			short stat, String lastUser, String equipmentType, Set<CurrentUserInfo> currentUserInfos,
			Set<QueryRecord> queryRecords) {
		this.equipmentId = equipmentId;
		this.driveTrainCompanyInfo = driveTrainCompanyInfo;
		this.equipmentCode = equipmentCode;
		this.stat = stat;
		this.lastUser = lastUser;
		this.equipmentType = equipmentType;
		this.currentUserInfos = currentUserInfos;
		this.queryRecords = queryRecords;
	}

	@Id

	@Column(name = "EQUIPMENT_ID", unique = true, nullable = false, length = 64)
	public String getEquipmentId() {
		return this.equipmentId;
	}

	public void setEquipmentId(String equipmentId) {
		this.equipmentId = equipmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_UNIT_CODE", nullable = false)
	public DriveTrainCompanyInfo getDriveTrainCompanyInfo() {
		return this.driveTrainCompanyInfo;
	}

	public void setDriveTrainCompanyInfo(DriveTrainCompanyInfo driveTrainCompanyInfo) {
		this.driveTrainCompanyInfo = driveTrainCompanyInfo;
	}

	@Column(name = "EQUIPMENT_CODE", nullable = false, length = 24)
	public String getEquipmentCode() {
		return this.equipmentCode;
	}

	public void setEquipmentCode(String equipmentCode) {
		this.equipmentCode = equipmentCode;
	}

	@Column(name = "STAT", nullable = false)
	public short getStat() {
		return this.stat;
	}

	public void setStat(short stat) {
		this.stat = stat;
	}

	@Column(name = "LAST_USER", length = 64)
	public String getLastUser() {
		return this.lastUser;
	}

	public void setLastUser(String lastUser) {
		this.lastUser = lastUser;
	}

	@Column(name = "EQUIPMENT_TYPE", nullable = false)
	public String getEquipmentType() {
		return this.equipmentType;
	}

	public void setEquipmentType(String equipmentType) {
		this.equipmentType = equipmentType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "simulatorInfo")
	public Set<CurrentUserInfo> getCurrentUserInfos() {
		return this.currentUserInfos;
	}

	public void setCurrentUserInfos(Set<CurrentUserInfo> currentUserInfos) {
		this.currentUserInfos = currentUserInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "simulatorInfo")
	public Set<QueryRecord> getQueryRecords() {
		return this.queryRecords;
	}

	public void setQueryRecords(Set<QueryRecord> queryRecords) {
		this.queryRecords = queryRecords;
	}

}
