package com.model.po;
// Generated 2018-7-6 14:29:52 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TrainingRecords generated by hbm2java
 */
@Entity
@Table(name = "TrainingRecords", catalog = "SimulatorManagement")
public class TrainingRecords implements java.io.Serializable {

	private String simulatorId;
	private String content;
	private String picpath;

	public TrainingRecords() {
	}

	public TrainingRecords(String simulatorId) {
		this.simulatorId = simulatorId;
	}

	public TrainingRecords(String simulatorId, String content, String picpath) {
		this.simulatorId = simulatorId;
		this.content = content;
		this.picpath = picpath;
	}

	@Id

	@Column(name = "simulatorId", unique = true, nullable = false)
	public String getSimulatorId() {
		return this.simulatorId;
	}

	public void setSimulatorId(String simulatorId) {
		this.simulatorId = simulatorId;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "picpath")
	public String getPicpath() {
		return this.picpath;
	}

	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

}
